// Shared Terms & Conditions copy, used by both /terms and the register-page dialog.
// Keep this plain text/JSX (no fetch) so it renders instantly inside a dialog.

export const TERMS_VERSION = '1.0';
export const TERMS_UPDATED = 'July 2026';

export default function TermsContent() {
  return (
    <div className="space-y-4 text-sm leading-relaxed text-slate-600">
      <p className="text-xs text-slate-400">Version {TERMS_VERSION} · Last updated {TERMS_UPDATED}</p>

      <section>
        <h3 className="font-semibold text-slate-800">1. About AgriSarthi AI</h3>
        <p>AgriSarthi AI is a voice-enabled farming assistant that provides crop, weather, mandi
        price, irrigation and advisory information to help you make farming decisions. It is a
        decision-support tool, not a substitute for professional agronomic, financial or legal advice.</p>
      </section>

      <section>
        <h3 className="font-semibold text-slate-800">2. Your account</h3>
        <p>You must provide accurate registration details and keep your password confidential. You
        are responsible for all activity carried out under your account. Tell us immediately if you
        believe your account has been accessed without your permission.</p>
      </section>

      <section>
        <h3 className="font-semibold text-slate-800">3. Data we store</h3>
        <p>We store the name, phone number and (hashed, never plain-text) password you register with.
        If you give consent inside the app, we may also store your farm profile — location, soil type,
        season, crop and irrigation preferences — so we can personalise recommendations. You can
        withdraw this consent at any time, which deletes your stored farm profile.</p>
      </section>

      <section>
        <h3 className="font-semibold text-slate-800">4. Accuracy of advice</h3>
        <p>Recommendations combine satellite, weather, market and rule-based agronomic data. Weather,
        market prices and pest/disease risk can change quickly and unpredictably. Always verify
        critical decisions — such as large input purchases or irrigation timing — with a local
        agriculture officer or trusted extension worker before acting.</p>
      </section>

      <section>
        <h3 className="font-semibold text-slate-800">5. Acceptable use</h3>
        <p>Do not use the app to submit false information, attempt to access other farmers' accounts
        or data, or interfere with the service's normal operation.</p>
      </section>

      <section>
        <h3 className="font-semibold text-slate-800">6. Limitation of liability</h3>
        <p>AgriSarthi AI is provided "as is". To the maximum extent permitted by law, we are not
        liable for crop loss, financial loss or other damages arising from reliance on advisory
        content generated by the app.</p>
      </section>

      <section>
        <h3 className="font-semibold text-slate-800">7. Changes to these terms</h3>
        <p>We may update these Terms from time to time. Continued use of the app after an update
        means you accept the revised Terms.</p>
      </section>
    </div>
  );
}
